name: Check with yarn
on: [push, pull_request]
jobs:
  build:
    name: Install and test with yarn
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["18.16.1", "18.17.1", "18.18.1"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: yarn install
      - run: yarn test
